/// Autogenerated by Targets - Edit tests.json instead of this file
import 'helpers.dart';
final String name = "Eclipse Targets Sample";
final String owner = "mvhs";
final String id = "eclipse-sample";
final List<String> files = ["Student.java"];
List<Target> getTargets() {
    var targets = [];
    targets.addAll(IOTarget.makeMultiJava("TestStudent", [new InputOutput.withArgs("Basic Functionality", "basic", "", 4), new InputOutput.withArgs("Grade String", "gradestring", "", 1), new InputOutput.withArgs("Sorting", "sort", "", 3), new InputOutput.withArgs("Average", "average", "", 2), ]));
    return targets;
}
